### ISSUE TITLE
Get metadata: "missing_SRP_column"

### ISSUE THREAD

**Issue by Alexander-Morin** [remap-cisreg/remap-pipeline#1]
Hey, 
I get error "missing_SRP_column" when executing 2.scripts/utils/python3/extract_info_download_v3_1.py. Changing the value on line 270 to 5 corrected this for me and successfully generated the report.
Thanks!

https://github.com/remap-cisreg/remap-pipeline/blob/52e45d8eb360f0fbd7d22209018cef510a9bd598/2.scripts/utils/python3/extract_info_download_v3_1.py#L270

**Comment by benoitballester** [comment]
Hi Alex, 
Yes you need to adjust the column number corresponding to your text file. 
Let me add @fayrouzhammal my PhD student in the loop, she took over the pipeline. 
She'll be able to confirm this. @fayrouzhammal can you confirm this is correct ?
Cheers,
Ben

**Comment by fayrouzhammal** [comment]
Hello,

Yes the script needs to be adjusted to your file by changing the number of
the communs.

Have a good day and don't hesitate to ask us if you have any problemes.

Sincerely yours,
Hammal Fayrouz

Le mar. 20 oct. 2020 à 10:19, Benoit Ballester <notifications@github.com> a
écrit :

**Comment by ilibarra** [comment]
@fayrouzhammal Hello. As far as I can see the main branch of this repository still uses `col_SRP = 6` and it crashes when running 
`python /mnt/znas/icb_zstore01/groups/ml01/workspace/ignacio.ibarra/theislab/remap-pipeline/2.scripts/utils/python3/extract_info/extract_info_download_v3_1.py -wd . -f 1.metadata/EXAMPLE_hsap_TF.tsv`
Could you please consider updating it? Thanks,
